name: CI-MAIN-Analytics-Service
on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:
  Call-Docker-Build-Main:
    uses: Wealth-Management-Project-v1/github-actions-reusable-workflows/.github/workflows/ci-branch.yaml@main

