name: wmp-ci-analytics-service
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Docker-Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - name: Docker build
        run: make docker-build
  eks-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
        with:
          repository: Wealth-Management-Project-v1/helm-v1
      - name: Helm deploy
        run: make eks-deploy