name: wmp-ci-analytics-service
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: docker-build
      - name: list
        run: ls -l